# add the following to _config.yml file
title: ASHHAB KARAMI
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

description: Showcasing my journey in data analytics and engineering through projects, tools, and insights that drive meaningful decisions
